### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by LoaderB0T** [lplawlor/lplawlor.github.io#1]
Hi there, I just saw that you used my package "typed.ts" on your portfolio website.

Very cool thanks a lot. Just wanted to know if you have any feedback or suggestions regarding the package.

Sorry for stalking & have a great one.

Best wishes,
Janik

**Comment by lplawlor** [comment]
Hi Janik.

Thanks for making typed.ts! It's a really well put together package. I honestly don't have any suggestions, it was easy to use and configure the text to type just how I wanted it.

Best,
Liam
